name = "SkyRoomsGtk"
uuid = "b4f94377-d82b-4c59-8521-c5b62fb81412"
authors = ["Yakir Gagnon <12.yakir@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"
GtkObservables = "8710efd8-4ad6-11eb-33ea-2d5ceb25a41c"
LibSerialPort = "a05a14c7-6e3b-5ba9-90a2-45558833e1df"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
Gtk = "1"
GtkObservables = "1"
LibSerialPort = "0.5.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
