[[setups]]
label = "1 green"

[[setups.suns]]
red = 0
green = 255
blue = 0
elevation = 1
radius = 0
cardinality = "NW"

[[setups]]
label = "2 colors"

[[setups.suns]]
red = 255
green = 0
blue = 0
elevation = 2
radius = 0
cardinality = "NW"

[[setups.suns]]
red = 0
green = 0
blue = 255
elevation = 3
radius = 0
cardinality = "NW"

[[setups]]
label = "off"

[[setups.suns]]
red = 0
green = 0
blue = 0
elevation = 1
radius = 0
cardinality = "NW"

[[setups]]
label = "4 corners"

[[setups.suns]]
red = 255
green = 255
blue = 255
elevation = 1
radius = 0
cardinality = "NE"

[[setups.suns]]
red = 255
green = 255
blue = 255
elevation = 1
radius = 0
cardinality = "SW"

[[setups.suns]]
red = 255
green = 255
blue = 255
elevation = 1
radius = 0
cardinality = "SE"

[[setups.suns]]
red = 255
green = 255
blue = 255
elevation = 1
radius = 0
cardinality = "NW"

[[setups]]
label = "NE center"

[[setups.suns]]
red = 255
green = 255
blue = 255
elevation = 71
radius = 0
cardinality = "NE"

[[setups]]
label = "SW center"

[[setups.suns]]
red = 255
green = 255
blue = 255
elevation = 71
radius = 0
cardinality = "SW"

[[setups]]
label = "SE center"

[[setups.suns]]
red = 255
green = 255
blue = 255
elevation = 71
radius = 0
cardinality = "SE"

[[setups]]
label = "NW center"

[[setups.suns]]
red = 255
green = 255
blue = 255
elevation = 71
radius = 0
cardinality = "NW"

[[setups]]
label = "cross"

[[setups.suns]]
red = 1
green = 1
blue = 1
elevation = 71
radius = 200
cardinality = "NE"

[[setups.suns]]
red = 255
green = 255
blue = 255
elevation = 71
radius = 200
cardinality = "NW"

[[setups]]
label = "wind1"

[[setups.suns]]
red = 0
green = 0
blue = 0
elevation = 1
radius = 1
cardinality = "NW"

[[setups.winds]]
id = 1
duty = 20
