[[setups]]
label = "1 green"

[[setups.suns]]
red = 0
green = 255
blue = 0
elevation = 1
radius = 0
cardinality = "NW"

[[setups]]
label = "2 colors"

[[setups.suns]]
red = 255
green = 0
blue = 0
elevation = 2
radius = 0
cardinality = "NW"

[[setups.suns]]
red = 0
green = 0
blue = 255
elevation = 3
radius = 0
cardinality = "NW"

[[setups]]
label = "4 corners"

[[setups.suns]]
red = 255
green = 255
blue = 255
elevation = 1
radius = 0
cardinality = "NE"

[[setups.suns]]
red = 255
green = 255
blue = 255
elevation = 1
radius = 0
cardinality = "SW"

[[setups.suns]]
red = 255
green = 255
blue = 255
elevation = 1
radius = 0
cardinality = "SE"

[[setups.suns]]
red = 255
green = 255
blue = 255
elevation = 1
radius = 0
cardinality = "NW"

[[setups]]
label = "NE center"

[[setups.suns]]
red = 255
green = 255
blue = 255
elevation = 71
radius = 0
cardinality = "NE"

[[setups]]
label = "cross"

[[setups.suns]]
red = 255
green = 255
blue = 255
elevation = 71
radius = 60
cardinality = "NE"

[[setups.suns]]
red = 255
green = 255
blue = 255
elevation = 71
radius = 60
cardinality = "NW"

[[setups]]
label = "colored cross"

[[setups.suns]]
red = 255
green = 0
blue = 0
elevation = 35
radius = 35
cardinality = "NE"

[[setups.suns]]
red = 0
green = 255
blue = 0
elevation = 35
radius = 35
cardinality = "NW"

[[setups.suns]]
red = 0
green = 0
blue = 255
elevation = 35
radius = 35
cardinality = "SE"

[[setups.suns]]
red = 255
green = 255
blue = 255
elevation = 35
radius = 35
cardinality = "SW"

[[setups]]
label = "a bit of wind"

[[setups.winds]]
id = 1
duty = 20

[[setups]]
label = "a bit of wind wth cross"

[[setups.suns]]
red = 255
green = 255
blue = 255
elevation = 71
radius = 200
cardinality = "NE"

[[setups.suns]]
red = 255
green = 255
blue = 255
elevation = 71
radius = 200
cardinality = "NW"

[[setups.winds]]
id = 1
duty = 20

[[setups]]
label = "all wind at 20%"

[[setups.winds]]
id = 1
duty = 51

[[setups.winds]]
id = 2
duty = 51

[[setups.winds]]
id = 3
duty = 51

[[setups.winds]]
id = 4
duty = 51

[[setups.winds]]
id = 5
duty = 51

[[setups]]
label = "max wind"

[[setups.winds]]
id = 1
duty = 254

[[setups.winds]]
id = 2
duty = 254

[[setups.winds]]
id = 3
duty = 254

[[setups.winds]]
id = 4
duty = 254

[[setups.winds]]
id = 5
duty = 254

